ALTER TABLE cities ALTER COLUMN name TYPE CHARACTER VARYING(30);

ALTER TABLE districts ALTER COLUMN name TYPE CHARACTER VARYING(30);

ALTER TABLE warehouses ALTER COLUMN address TYPE CHARACTER VARYING(30);

ALTER TABLE couriers ALTER COLUMN name TYPE CHARACTER VARYING(30);

ALTER TABLE vehicles ALTER COLUMN typeOfVehicle TYPE CHARACTER VARYING(30);