INSERT INTO cities VALUES (1, 'Kazan');
INSERT INTO cities VALUES (2, 'Rome');
INSERT INTO districts VALUES (1, 1,  'District 1');
INSERT INTO districts VALUES (2, 2, 'District 2');
INSERT INTO warehouses VALUES (1, 1, 'Pushkina');
INSERT INTO warehouses VALUES (2, 2, 'Kolotushkina');
INSERT INTO couriers VALUES (1, 1, 'Alexandr', 1);
INSERT INTO couriers VALUES (2, 2, 'Ciro', 12);
INSERT INTO vehicles VALUES (1, 1, 'byke');
INSERT INTO vehicles VALUES (2, 2, 'car');
INSERT INTO products VALUES (1, 'milk', 10);
INSERT INTO products VALUES (2, 'chocolate', 15);
INSERT INTO warehouse_product VALUES (1, 1);
INSERT INTO warehouse_product VALUES (2, 2);
INSERT INTO orders VALUES (1, 1, 'Peschanaya');
INSERT INTO orders VALUES (2, 10, 'Suhaya');
INSERT INTO order_product VALUES (1, 1);
INSERT INTO order_product VALUES (2, 1);
INSERT INTO order_product VALUES (2, 2);
INSERT INTO users VALUES (1, 'Mostovoy', 'Moskovskaya');
INSERT INTO users VALUES (2, 'Kean', 'Via Vittorio Veneto');